### PR TITLE
feat(package)!: the repo is now a unity package

### PR DESCRIPTION
**Pull request by Morgan-6Freedom**
@mrbusysky I have drastically changed the folders.

## About installation :

With this new structure, users will be able to add the plugin really easily :
1. Open Unity
2. Window=>PackageManager=>[+]
3. Copy paste this link : https://github.com/scenario-labs/Scenario-Unity.git
image

No need for a zip file or a release tab in the github anymore !

## About github actions

The package.json that was refering to the github actions was putted in the Github Action folder.
GithubActions~/ folder has a ~ to specify to Unity that it should not downlod this from the package manager.

So I imagine that the github actions won't work anymore with this folder structure :

1. Why do we need thoses gitub action ?
4. I think we can remove it, what do you think ?

### CODE REVIEW

**Comment by qvaleroo** [comment]
The github action release-please is used to generate a PR automatically with a changelog based on merged PR + release number increase (example here: https://github.com/scenario-labs/Scenario-Unity/pull/86). Doc here: https://github.com/googleapis/release-please
Then when this PR is merged, it automatically add a tag, and so we have the changelog and the version in the Release tab of GitHub: https://github.com/scenario-labs/Scenario-Unity/releases

If we delete the github action, how do we build the changelog, and how can we communicate on a new version available and the release note?

**Comment by Morgan-6Freedom** [comment]
1. We don't need a release page anymore on github. Because people will use a link instead of a zip file.
2. about the changelog : either the developers write it when they do their PR, either we fix the github action to automatically fill the changelog

**Comment by Morgan-6Freedom** [comment]
ok now everything that is Unity related is under /package folder
Github actions should work as expected.
And I changed the readme to explain how to install it

**Comment by Morgan-6Freedom** [comment]
We still need to update this page : https://help.scenario.com/installing-the-unity-plugin

**Review by qvaleroo — APPROVED** [review]

**Pull request merged**
