### PR TITLE
fix: adding scheduler reception and displaying

### PR DESCRIPTION
**Pull request by TheLLspectre**
The selected scheduler is now displayed in the description image.

image

- closes: #136

### CODE REVIEW

**Review by Morgan-6Freedom — DISMISSED** [review]

**Comment by qvaleroo** [comment]
Right after generation, we have a wrong value of Scheduler, set to Default. I had to close and reopen Images window to see the correct value:
image

**Comment by Morgan-6Freedom** [comment]
@TheLLspectre still waiting for your fix on this

**Comment by TheLLspectre** [comment]
That wasn't really easy but I found it !

**Comment by Morgan-6Freedom** [comment]
@qvaleroo waiting for you to validate the fix =)

**Comment by qvaleroo** [comment]
QA OK 👍

**Review by qvaleroo — APPROVED** [review]

**Pull request merged**
