### PR TITLE
fix(promptwindow): invert the influence value to make more sense and match the webapp - closes #123

### LINKED ISSUE #123: Invert the Influence value to make more sense and match the Webapp.
Currently the default influence value is 0.25 which is relative to 0.75 in the webapp, although the value is actually inverted in the webapp I suggest inverting it to match the webapp.

### PR DESCRIPTION
**Pull request by Morgan-6Freedom**
see #123

### CODE REVIEW

**Comment by qvaleroo** [comment]
Influence should go from 0 to 99
Then strenght will be `100 - influence`

**Comment by qvaleroo** [comment]
Maybe it worths to add the info of Influence on Image details?
image

**Comment by Morgan-6Freedom** [comment]
ref from the website : 
image

**Comment by Morgan-6Freedom** [comment]
> Maybe it worths to add the info of Influence on Image details? image

It would be for another ticket "Put the reference image and its influence in the detail of a generated image"

**Review by qvaleroo — APPROVED** [review]

**Pull request merged**
