### PR TITLE
fix: 125 control net options should have the same naming as on the webapp

### PR DESCRIPTION
**Pull request by TheLLspectre**
Now according to modalities available on the webapp and SDXL / SD 1.5 tags, we have same options available on Unity plugin. 
Adding an array of translation of those modalities to manage api request and displaying interface in Unity.
Also renaming some variables.

image

image

- closes: #125

### CODE REVIEW

**Comment by Morgan-6Freedom** [comment]
@TheLLspectre still waiting for your fixes on this

**Comment by TheLLspectre** [comment]
How to reproduce this ?? I don't have this behaviour :/

> Opening prompt window without modifying the model does not prefill Modalities value: image

**Comment by qvaleroo** [comment]
I do not reproduce, after starting from scratch. Let's merge. I let you handle conflicts

**Comment by TheLLspectre** [comment]
> I do not reproduce, after starting from scratch. Let's merge. I let you handle conflicts

The only way I had to reproduce it, it's on a first install and launch, when I don't have any model selected and here I don't had modalities but it's normal

**Comment by TheLLspectre** [comment]
@qvaleroo @Morgan-6Freedom 

I managed conflict with a merge dev into branch !

**Review by qvaleroo — APPROVED** [review]

**Pull request merged**
