### PR TITLE
fix(versionumber): the updateversionfrompackagejson function should not use a static path

### PR DESCRIPTION
**Pull request by Morgan-6Freedom**
it now use a dynamic path based on the assembly definition

### CODE REVIEW

**Comment by Morgan-6Freedom** [comment]
> Is this version number used only to be displayed on settings?

Yes it is only used there.

> Does it take the version number from Scenario/package.json, or root package.json? Currently, our release-please CI update the root package.json. I haven't found a way to update the one in Scenario yet through the CI.

It takes the version number from the same file as before : Scenario/package.json

Why is there two of them ?

**Comment by qvaleroo** [comment]
The on at the root level is the one of the repo with dev dependencies and repo version for release numbers and tag.
The one at the root of Scenario is used inside the plugin.

The issue we have is that the one at the root level is automatically updated by the CI when we release, but not the one in Scenario folder. Can we merge both to have everything at root level?

**Comment by Morgan-6Freedom** [comment]
If https://github.com/scenario-labs/Scenario-Unity/pull/106 this PR pass, this one will be out of date.
I will fix it after the PR 106 is accepted

**Comment by Morgan-6Freedom** [comment]
@qvaleroo this is now ok from develop. Can merge into dev

**Review by qvaleroo — APPROVED** [review]

**Pull request merged**
