### PR TITLE
fix: downloading size on image window

### PR DESCRIPTION
**Pull request by TheLLspectre**
Also impact other downloading option like sprite or texture. Have to update thoses actions too.

- closes: #158 

Have to see if this have impact on memory ?

### CODE REVIEW

**Comment by Morgan-6Freedom** [comment]
Could we get a couple of videos that shows the difference (before/after) over memory and loading time ?
It could be great to show off this new improvement =)

**Comment by Morgan-6Freedom** [comment]
@TheLLspectre please resolve conflict then I'll be ok to merge it

**Review by Morgan-6Freedom — APPROVED** [review]

**Comment by Morgan-6Freedom** [comment]
I'll wait for @qvaleroo to check before merging

**Comment by qvaleroo** [comment]
QA OK 👍

**Pull request merged**
